[package]
name = "gdamjan-tgbot"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
bytes = "1"
# http = "1"
minijinja = { version = "2", features = ["loader"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
spin-sdk = "4"
