spin_manifest_version = 2

[application]
name = "gdamjan-tgbot"
version = "0.1.0"
description = "A wasm telegram bot"
authors = ["Дамјан Георгиевски <gdamjan@gmail.com>"]


[variables]
telegram_token = { required = true }

[[trigger.http]]
route = "/..."
component = "tgbot"

[component.tgbot]
source = "target/wasm32-wasip2/release/gdamjan_tgbot.wasm"
files = [{ source = "src/templates/", destination = "/templates/" }]
allowed_http_hosts = ["api.telegram.org"]
key_value_stores = ["default"]

[component.tgbot.variables]
telegram_token = "{{ telegram_token }}"
telegram_api_endpoint = "https://api.telegram.org/bot{{ telegram_token }}"

[component.tgbot.build]
command = "cargo build --target wasm32-wasip2 --release"
watch = ["src/**/*", "Cargo.toml"]
